version: '2'

services:
  db:
    image: mariadb
    container_name: mysql
    ports:
      - "3307:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=marketplace
      - MYSQL_USER=marketplace
      - MYSQL_PASSWORD=marketplace

  rabbitmq:
      image: rabbitmq:management-alpine
      container_name: rabbitmq
      ports:
        - "5671:5671"
        - "5672:5672"
        - "15672:15672"
      environment:
        - RABBITMQ_DEFAULT_USER=marketplace
        - RABBITMQ_DEFAULT_PASS=marketplace
